name: Go test

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Install Dependencies
           run: |
              sudo apt-get update
              sudo apt-get install -y libvips libvips-dev libvips-tools

         - name: Set up Go
           uses: actions/setup-go@v4
           with:
              go-version: "1.22"

         - name: Build
           run: go build -v ./...

         - name: Test
           run: go test -v ./...
